### ISSUE TITLE
[Bug] Shop Down, keeps showing Connection Error

### ISSUE THREAD

**Issue by LGM-Productions** [Cube-Enix/SNext#15]
**Type of Bug**
- [ ] UI (Problems with the console itself)
- [ ] Install (Problems with installing the console)
- [ ] Boot (Problems with loading or opening games)
- [✅ ] Shop (Problems with the eShop)
- [ ] Online (Problems with other Online Features)
- [ ] Other

Issue:
The shop won't work. Even though I'm connected to the internet

Expected behavior:
Once you are connected, it would show the shop UI.

Screenshots:
![image](https://user-images.githubusercontent.com/96096550/179334027-9d85dcb6-4616-47f3-970d-6a2193da9820.png)

Specs:
 - OS: Windows 11
 - Browser: Google Chrome 103.0.5060.114 (Official Build) (64-bit)
 - Console Build Version: Release 1.1.0

Additional context:
None

**Comment by ShipmasterKyle** [comment]
We are well aware that the shop is down. Theres a problem with our servers rn that we are working on fixing.
