### ISSUE TITLE
Its not installing

### ISSUE THREAD

**Issue by BenWasTakenReddit** [Cube-Enix/SNext#20]
**Type of Bug**
- [ ] UI (Problems with the console itself)
- [X] Install (Problems with installing the console)
- [ ] Boot (Problems with loading or opening games)
- [ ] Shop (Problems with the eShop)
- [ ] Online (Problems with other Online Features)
- [ ] Other

**Describe the problem**

whenever i try to build the latest version it doesnt seem to install and when i run the installer bat file it just closes

**To Reproduce**

i just run the installer

**Expected behavior**

I expected it to install

**Screenshots**

**Specs:**

 - OS: [Windows 11, x64]
 - Console Build Version: [Whatever the latest one is]

**Additional context**

**Comment by ShipmasterKyle** [comment]
Did you try running the batch file in the terminal console?

**Comment by BenWasTakenReddit** [comment]
i fixed it
