### ISSUE TITLE
Javascript error when i try to run

### ISSUE THREAD

**Issue by BenWasTakenReddit** [Cube-Enix/SNext#21]
**Type of Bug**
- [ ] UI (Problems with the console itself)
- [X] Install (Problems with installing the console)
- [X] Boot (Problems with loading or opening games)
- [ ] Shop (Problems with the eShop)
- [ ] Online (Problems with other Online Features)
- [ ] Other

**Describe the problem**

i get a Javascript error when i try to launch

**To Reproduce**

i just run npm start in the src folder

**Expected behavior**

I expected it to run

**Screenshots**

![Screenshot 2022-09-13 173901](https://user-images.githubusercontent.com/79175034/189840407-d5f29673-1d0f-4283-a833-0aa610d2fd14.png)

**Specs:**

 - OS: [Windows 11, x64]
 - Console Build Version: [Latest]

**Additional context**

**Comment by BenWasTakenReddit** [comment]
wait it still launched

**Comment by ShipmasterKyle** [comment]
Possible duplicate of #18
