### ISSUE TITLE
Unable to be built with Powershell.

### ISSUE THREAD

**Issue by Kaylerr** [Cube-Enix/SNext#4]
It shows up with the NPM install instructions, but does not action on them. and shows an error, usually nullifying.

**Comment by Kaylerr** [comment]
it appears as if installing the latest powershell i could find (7.2) and reinstalling all my powershell files and reconfiguring and rearranging some stuff in the source code, it fixed it??

**Comment by ShipmasterKyle** [comment]
Powershell is very iffy to start but considering that we've already begun the process of deprecating that install method in favor of batch.
